export default {
  index: { display: 'hidden' },
  'binance-stamp': 'Binance Stamp',
  'biometrics-stamp': 'Biometrics Stamp',
  'discord-stamp': 'Discord Stamp',
  'ens-stamp': 'ENS Stamp',
  'ethereum-stamp': 'Ethereum Stamp',
  'gitcoin-stamp': 'Gitcoin Stamp',
  'github-stamp': 'GitHub Stamp',
  'google-stamp': 'Google Stamp',
  'safe-stamp': 'Safe Stamp',
  'x-stamp': 'X Stamp (Retired)',
  'steam-stamp': 'Steam Stamp',
  'guild-stamp': 'Guild.xyz Stamp',
  'government-id-stamp': 'Government ID Stamp',
  'identity-staking-stamp': 'Identity Staking (GTC) Stamp',
  'linkedin-stamp': 'LinkedIn Stamp',
  'nft-stamp': 'NFT Stamp',
  'phone-stamp': 'Phone Verification Stamp',
  'proof-of-clean-hands-stamp': 'Proof of Clean Hands Stamp',
  'snapshot-stamp': 'Snapshot Stamp',
  'zk-email-stamp': 'ZK Email Stamp',
}
